import { parseTypeAnnotation, parseCommentBlock } from "./parser";
import { LINE_BREAK } from "./constant";

export function generateMarkdown(interfaceCollection: any[]) {
  const mdTitle = "## API";

  const mdTemplate = [
    "| 属性名 | 描述 | 类型 | 必需 | 默认值",
    "| ----------- | ----------- |---------- |---------- |---------- |",
  ];

  const extraInfo = [
    "The API Document is generated by typescript-doc-gen!",
    "Author: Oliver <matthrews@outlook.com>",
    "License: MIT",
    "Repo: https://github.com/Matthrews/typescript-doc-gen",
  ];

  const bodyContent: string[] = [];

  interfaceCollection.forEach((interfaceItem) => {
    const {
      id: { name = "" },
      body: { body: properties = [] },
    } = interfaceItem;
    const contents = [`### ${name}${LINE_BREAK}`].concat(mdTemplate);

    properties.forEach((property: any) => {
      const {
        optional,
        key: { name = "" },
        leadingComments: [{ value = "" }],
        typeAnnotation: { typeAnnotation = {} },
      } = property;
      const type = parseTypeAnnotation(typeAnnotation);
      const required = optional ? "--" : "是";
      const comment = parseCommentBlock(value);
      const note = parseCommentBlock(value, "note");

      const defaultValue = parseCommentBlock(value, "default") || "--";
      contents.push(
        `| ${name} | ${comment} ${
          note ? `<br/> ${note}` : ""
        } | <code>${type}</code> | <code>${required}</code> | <code>${defaultValue}</code> |`
      );
    });

    contents.push(LINE_BREAK);

    bodyContent.push(contents.join(LINE_BREAK));
  });

  return [mdTitle].concat(bodyContent).concat(extraInfo).join(LINE_BREAK);
}
